language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_script:
  - pip -q install -r requirements.txt
  - cp config_test.cfg config.cfg
  - mysql -e 'create database pkpplntest;'
  - mysql pkpplntest < pkppln-test.sql
  - sudo mysql -e "grant all on pkpplntest.* to pkpplntest@localhost identified by 'abc123456'"
  - sudo touch /var/log/pkppln.log
  - python server.py config_test.cfg > server.log 2>&1 &
  - sleep 4

script:
  - python -m unittest discover tests
  
after_script:
  - killall python
  - cat server.log
  - cat /var/log/pkppln.log
