language: python

python:
  - "2.7"

install:
  - pip install mysql-python
  - pip install bottle


script:
  - cp config_sample.cfg config.cfg
  - python feeds/feed_server.py > srv.log 2>&1 &
  - python -m unittest discover test
  - killall python
  - cat srv.log
  
