language: python

python:
  - "2.7"

before_script:
  - pip -q install -r requirements.txt
  - cp config_travis.cfg config.cfg
  - mysql -e 'create database pkpplntest;'
  - mysql pkpplntest < pkppln.sql
  - mysql -e "grant all on pkpplntest.* to pkpplntest@localhost identified by 'abc123'"
  - python server.py > server.log &
  - sleep 4

script:
  - python -m unittest discover tests
  
after_script:
  - killall python
  - cat server.log
  
