language: python

python:
  - "2.7"

before_script:
  - pip install mysql-python
  - pip install bottle
  - cp config_sample.cfg config.cfg
  - mysql -e 'create database mypln;'
  - mysql mypln < pkppln.sql

script:
  - python feeds/feed_server.py > srv.log 2>&1 &
  - python -m unittest discover test
  - killall python
  - cat srv.log
