language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_script:
  - pip -q install -r requirements.txt
  - mysql -e 'create database pkpplntest;'
  - mysql pkpplntest < pkppln.sql
  - sudo mysql -e "grant all on pkpplntest.* to pkpplntest@localhost identified by 'abc123'"
  - python server.py config_test.cfg > server.log &
  - sleep 4

script:
  - python -m unittest discover tests
  
after_script:
  - killall python
  - cat server.log
  
